version: '3'
services:
  gitslackbot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - logs:/app/logs
    restart: always
volumes:
  logs: